### ISSUE TITLE
ibmcom/ace-mq startup issue using Helm Chart

### ISSUE THREAD

**Issue by bhubanpadhan** [ot4i/ace-docker#77] opened 2019-08-08 11:42 UTC
Hello,
My team has pulled the image ibmcom/ace-mq and created the custom queue manager. When deploying this new image using Kubernetes command (kubectl apply) the queue manager starts automatically in the container, but when the same image is deployed using the Helm chart, the queue manager status shows always "Starting".

Could some one please help on this issue? Is this related to https://github.com/ibm-messaging/mq-container/issues/207 ?

Thanks and regards,
Bhuban

**Comment by IBMRob** [comment] 2019-08-08 12:02
Hi,

When you say "created the custom queue manager" what do you mean?

If the container does not startup up when using helm but does using kubectl I suggest using helm xxxxxxx --dry-run --debug to get the output from helm and compare it to the kubectl yams you are deploying manually. It should highlight a difference

**Comment by bhubanpadhan** [comment] 2019-08-09 17:52
Hi Rob,

Thank you for the suggestion.  The issue is resolved.
The length of the pod, service and deployment names are 52, 35 and 35 characters respectively.  Changed the name size to 45  characters (pod name),  28 characters (service and deployment name) and now queue manager is starting as expected.  I am not sure what is the expected size.

**Comment by IBMRob** [comment] 2019-08-22 06:49
Closing this issue given the problem is resolved and no more information on the customisation has been provided

**Closed by IBMRob** 2019-08-22 06:49 UTC
