### ISSUE TITLE
Integration server not ready yet

### ISSUE THREAD

**Issue by har2103** [ot4i/ace-docker#47] opened 2019-06-13 18:51 UTC
I am running ACE + MQ in OpenShift. and mounting to dir "/home/aceuser" and "/home/aceuser/initial-config". also placing server-config.ymal file in initial-config dir.

When i am restarting my pod its not coming up. am getting below error.

2019-06-13T16:54:58.449Z Integration server not ready yet
IBM App Connect Enterprise v11004 (integration_server.ace) [Thread 561] (Msg 1/1) BIP2229W: Warning: abend file directory (/home/aceuser/ace-server/config/common/errors) open failed: errno 2. Using directory /tmp 0
IBM App Connect Enterprise v11004 (integration_server.ace) [Thread 561] (Msg 1/1) BIP2229W: Warning: abend file directory (/home/aceuser/ace-server/config/common/errors) open failed: errno 2. Using directory /tmp 0
Failed to open file /home/aceuser/ace-server/config/common/log/integration_server.ace.trace.0.txt with error No such file or directory
Caught unhandled exception in main: BIP2112E: IBM App Connect Enterprise internal error: diagnostic information ''No such file or directory'', '2'. : /jenkins/workspace/S000_Ubuntu_Linux_Build_And_Test/product-build/WMB/src/CommonServices/Unix/ImbFile.cpp: 452: ImbFile::getSize: : 
2019-06-13T16:55:03.453Z Integration server not ready yet

**Comment by IBMRob** [comment] 2019-06-13 19:37
Hi @har2103 

I suspect the problem is due to mounting over /home/aceuser. This will have removed all the directories that have been primed by https://github.com/ot4i/ace-docker/blob/master/ubuntu/Dockerfile.acemq#L59

Generally we would recommend against mounting over /home/aceuser, doing this restricts the ability to use capabilities such as scaling of pods etc.

**Comment by har2103** [comment] 2019-06-14 09:45
So how should I persist all the app deployed on ace server. And what is recommended dir which I should mount?

**Comment by IBMRob** [comment] 2019-06-14 09:57
What data are you trying to persist? You are mounting the initial-config so if the container gets restarted it will pick up the same config as the original one.

When moving to containers you don't want to be making live changes to the container, if you want to make changes you make those changes to either the initial-config or built into the actual container and then update your deployment to pick up the change.

**Comment by IBMRob** [comment] 2019-07-05 07:10
Closing this issue due to no update in 14 days

**Closed by IBMRob** 2019-07-05 07:10 UTC
Labels: help wanted
