### ISSUE TITLE
Cannot put messages into a queue using amqsputc from outside Docker

### ISSUE THREAD

**Issue by patrick-marie** [ot4i/ace-docker#24] opened 2019-02-25 23:15 UTC
I was able to run the CallMQMultiEcho application from within Docker, but not from outside. I could not use amqsputc to put a message into the input queue:
$ sudo docker exec -e MQSAMP_USER_ID=aceuser -e MQSERVER='ACE.SVRCONN/TCP/localhost(1414)' -it acemqapp /opt/mqm/samp/bin/amqsputc MULTIIN QMGR
Returned:
/opt/mqm/samp/bin/amqsputc: error while loading shared libraries: libmqic_r.so: cannot open shared object file: No such file or directory
I then searched libmqic_r.so in the Docker image but could not find it. It seems that the MQ client is not installed in the Docker image.
Any idea?

**Comment by IBMRob** [comment] 2019-02-26 09:04
The image does have the MQ client installed, both it and the server are installer together. This is shown by the fact the command will run within the container. I suspect the problem is around the environment, note that running a command within a container runs within different environment to that when run through an exec command.

I would attempt to run the command using /bin/sh -c "https://github.ibm.com/Cloud-Integration/firefly-iiboc-endusertest/issues/172" which would run the command with a similar environment

**Comment by patrick-marie** [comment] 2019-02-26 09:50
Thanks for your answer.
Referring to https://github.com/ot4i/ace-docker/blob/master/sample/README.md, the command run inside the container is not the same as outside ("amqsput" instead of "amqsputc"). I was also able to run "amqsput" from outside the container ("sudo docker exec -e MQSAMP_USER_ID=aceuser -it acemqapp /opt/mqm/samp/bin/amqsput MULTIIN QMGR"). The problem with "amqsputc" seems to be that the file "libmqic_r.so" is missing in the container (I connected to the container with "sudo docker exec -i -t acemqapp /bin/bash" and searched it with "find").

**Comment by IBMRob** [comment] 2019-02-26 12:27
Ah apologies I did not spot the difference in commands. Our image is built on top of the MQ image. It might be worth trying to run a simple MQ only container to check it also occurs there. If it does then I would raise it at https://github.ibm.com/mqoc/mq-container.

**Comment by patrick-marie** [comment] 2019-03-01 00:02
I was not able to connect to https://github.ibm.com/mqoc/mq-container, but I tried with: https://github.com/ibm-messaging/mq-container/tree/9.0.5. I created an MQ image and container and, again, I had the same error:
'/opt/mqm/samp/bin/amqsputc: error while loading shared libraries: libmqic_r.so: cannot open shared object file: No such file or directory'
when trying to put a message into a queue with 'amqsputc'.
I also checked that 'libmqic_r.so' is missing in the directories below '/opt/mqm'.
My understanding is that this library is missing because these images were built without selecting the 'MQSeriesClient' package for the MQ installation in their Dockerfile.
I think that you should modify the example showing how to run the 'CallMQMultiEcho' test application to use 'amqsput' instead of 'amqsputc'.

**Comment by IBMRob** [comment] 2019-03-01 08:01
I would suggest raising an issue against 
https://github.ibm.com/mqoc/mq-container to get this fixed in the latest release. To work around it for now you could supply argument of `BASE_IMAGE=ibmcom/mq:9.0.5.0` when building your image.

**Comment by patrick-marie** [comment] 2019-03-01 10:16
I cannot get access to:
https://github.ibm.com/mqoc/mq-container, but I opened an issue at: https://github.com/ibm-messaging/mq-container/issues/281. However, I expect the MQ people to answer me that the fact that the MQSeriesClient was not included when generating the image is not a bug, but a feature, and that the people using the resulting image must do with that feature.

**Comment by IBMRob** [comment] 2019-03-01 11:13
Apologies -I should've provided a link to 
https://github.com/ibm-messaging/mq-container. If MQ do come back with that response the only option will be to build your own MQ image and then use it as the base for your ACE image. As we are building on top of the MQ image we can only provide what they provide in their base image.

**Comment by patrick-marie** [comment] 2019-03-01 12:56
Here is the answer of the MQ people:

"Hi @patrick-marie - MQ 9.0.5.0 is no longer in support due to the Continous delivery support model that was in effect when 9.0.5 was released that stated we will support the latest 2 release. For reference the latest two releases are 9.1.0 and 9.1.1). The new support model that came into effect in 9.1 now says that we will support a CD release for a year or if 2 other releases are made (whichever is longer).

**That said.** Yes you are correct, if you've built an image of MQ which does not install the Client packages then you will not have the client libraries needed by MQ client applications to run. You can fix this by supplying the make argument `MQ_PACKAGES ` with the packages you want to install. The defaults are:

    * "MQSeriesRuntime-_.rpm MQSeriesServer-_.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm MQSeriesSamples*.rpm MQSeriesAMS-_.rpm MQSeriesWeb-_.rpm" for ubuntu

    * "MQSeriesRuntime-_.rpm MQSeriesServer-_.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm MQSeriesSamples*.rpm MQSeriesAMS-_.rpm MQSeriesWeb-_.rpm" for RHEL/Linux"

**Comment by IBMRob** [comment] 2019-03-01 14:32
You will need to build your own MQ container as per their recommendations if you want the MQ Client.

**Comment by IBMRob** [comment] 2019-03-05 16:20
Given that this is not a problem with the code in this repo I am going to close this. Feel free to reopen if you find a bug

**Closed by IBMRob** 2019-03-05 16:20 UTC
